@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bilibili.player_ix.noixmod_api.entities.monster;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;