
package com.bilibili.player_ix.noixmod_api.register;

import org.NineAbyss9.annotation.PAMAreNonnullByDefault;
import com.bilibili.player_ix.noixmod_api.NoixmodAPI;
import com.bilibili.player_ix.noixmod_api.entities.boss.*;
import com.bilibili.player_ix.noixmod_api.entities.boss.abyss.Abyss;
import com.bilibili.player_ix.noixmod_api.entities.boss.priest.Priest;
import com.bilibili.player_ix.noixmod_api.entities.boss.star_guardian.StarGuardian;
import com.bilibili.player_ix.noixmod_api.entities.monster.*;
import com.bilibili.player_ix.noixmod_api.entities.monster.horror.Detractor;
import com.bilibili.player_ix.noixmod_api.entities.monster.horror.Tracker;
import com.bilibili.player_ix.noixmod_api.entities.monster.hostile.HostileWindZombie;
import com.bilibili.player_ix.noixmod_api.entities.monster.illager.*;
import com.bilibili.player_ix.noixmod_api.entities.monster.nihilist.*;
import com.bilibili.player_ix.noixmod_api.entities.npc.DanDing.DanDa;
import com.bilibili.player_ix.noixmod_api.entities.projectile.*;
import com.bilibili.player_ix.noixmod_api.entities.projectile.arrow.ArrowArrowEntity;
import com.bilibili.player_ix.noixmod_api.entities.projectile.arrow.NihilisticArrow;
import com.bilibili.player_ix.noixmod_api.entities.projectile.arrow.VampireArrow;
import com.bilibili.player_ix.noixmod_api.entities.projectile.summon.SummonApostle;
import com.bilibili.player_ix.noixmod_api.entities.projectile.summon.SummonEntity;
import com.bilibili.player_ix.noixmod_api.entities.projectile.summon.SummonZhuan;
import com.bilibili.player_ix.noixmod_api.entities.servant.*;
import com.bilibili.player_ix.noixmod_api.entities.servant.animal.MushroomSpider;
import com.bilibili.player_ix.noixmod_api.entities.servant.end.EnderManServant;
import com.bilibili.player_ix.noixmod_api.entities.servant.illager.*;
import com.bilibili.player_ix.noixmod_api.entities.servant.nether.LavaZombieServant;
import com.bilibili.player_ix.noixmod_api.entities.servant.nether.NetherSoul;
import com.bilibili.player_ix.noixmod_api.entities.servant.nether.WitherSkeletonServant;
import com.bilibili.player_ix.noixmod_api.entities.servant.nihilistic.*;
import com.bilibili.player_ix.noixmod_api.entities.servant.sculk.SculkZombie;
import com.bilibili.player_ix.noixmod_api.entities.servant.sculk.warden.WardenEntitySensor;
import com.bilibili.player_ix.noixmod_api.entities.servant.sculk.warden.WardenServant;
import com.bilibili.player_ix.noixmod_api.entities.servant.worm.AquaticWorm;
import com.bilibili.player_ix.noixmod_api.entities.servant.worm.FreakyWorm;
import com.bilibili.player_ix.noixmod_api.entities.servant.worm.Worm;
import com.bilibili.player_ix.noixmod_api.entities.villager.*;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.entity.ai.sensing.SensorType;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

@PAMAreNonnullByDefault
@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class NoixmodAPIEntities {
    public static final DeferredRegister<EntityType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, NoixmodAPI.MOD_ID);
    public static final DeferredRegister<SensorType<?>> SENSORS = DeferredRegister.create(ForgeRegistries
            .SENSOR_TYPES, NoixmodAPI.MOD_ID);
    public static final RegistryObject<SensorType<WardenEntitySensor<WardenServant>>> WARDEN_SERVANT_SENSOR
            = SENSORS.register("warden_servant", () -> new SensorType<>(WardenEntitySensor::new));
    public static final RegistryObject<EntityType<Abomination>> ABOMINATION = register("abomination", EntityType.Builder.of(Abomination::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<Abyss>> ABYSS = register("abyss", EntityType.Builder.of(Abyss::new, MobCategory.MONSTER).sized(0.6f, 1.95f).fireImmune().clientTrackingRange(10));
    public static final RegistryObject<EntityType<Ambusher>> AMBUSHER = NoixmodAPIEntities.register("ambusher", EntityType.Builder.of(Ambusher::new, MobCategory.MISC).sized(0.6F, 1.95F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<ApostleBoss>> APOSTLE = NoixmodAPIEntities.register("apostle", EntityType.Builder.<ApostleBoss>of(ApostleBoss::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setCustomClientFactory(ApostleBoss::new).sized(0.6f, 2f).fireImmune());
    public static final RegistryObject<EntityType<ApostleServant>> APOSTLE_SERVANT = NoixmodAPIEntities.register("apostle_servant", EntityType.Builder.of(ApostleServant::new, MobCategory.MISC).sized(0.6f, 2f).fireImmune().setTrackingRange(128));
    public static final RegistryObject<EntityType<ApostleShadow>> APOSTLE_SHADOW = NoixmodAPIEntities.register("apostle_shadow", EntityType.Builder.<ApostleShadow>of(ApostleShadow::new, MobCategory.MISC).setCustomClientFactory(ApostleShadow::new).sized(0.6f, 1.95f).fireImmune());
    public static final RegistryObject<EntityType<AquaticWorm>> AQUATIC_WORM = NoixmodAPIEntities.register("aquatic_worm", EntityType.Builder.<AquaticWorm>of(AquaticWorm::new, MobCategory.MONSTER).sized(1f, 1f).setUpdateInterval(2));
    public static final RegistryObject<EntityType<ArcherServant>> ARCHER_SERVANT = register("archer_servant", EntityType.Builder.of(ArcherServant::new, MobCategory.MISC).sized(0.6f, 1.95f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<Armorer>> ARMORER = NoixmodAPIEntities.register("armorer", EntityType.Builder.of(Armorer::new, MobCategory.MONSTER).sized(0.6F, 1.95F));
    public static final RegistryObject<EntityType<ArrowArrowEntity>> ARROW_ARROW = NoixmodAPIEntities.register("arrow_arrow", EntityType.Builder.<ArrowArrowEntity>of(ArrowArrowEntity::new, MobCategory.MISC).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<BlackHole>> BLACK_HOLE = NoixmodAPIEntities.register("black_hole", EntityType.Builder.of(BlackHole::new, MobCategory.MISC).sized(2f, 2f).clientTrackingRange(10));
    public static final RegistryObject<EntityType<Biologist>> BIOLOGIST = NoixmodAPIEntities.register("biologist", EntityType.Builder.<Biologist>of(Biologist::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(12).setUpdateInterval(3).sized(0.6f, 1.95f).setCustomClientFactory(Biologist::new).fireImmune());
    public static final RegistryObject<EntityType<Bugler>> BUGLER = NoixmodAPIEntities.register("bugler", EntityType.Builder.of(Bugler::new, MobCategory.MONSTER).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Cage>> CAGE = register("cage", EntityType.Builder.of(Cage::new, MobCategory.MISC).sized(1f, 1.2f));
    public static final RegistryObject<EntityType<CreeperServant>> CREEPER_SERVANT = register("creeper_servant", EntityType.Builder.of(CreeperServant::new, MobCategory.MISC).sized(0.6F, 1.9F));
    public static final RegistryObject<EntityType<Cultist>> CULTIST = NoixmodAPIEntities.register("cultist", EntityType.Builder.<Cultist>of(Cultist::new, MobCategory.MONSTER).updateInterval(2).sized(0.6f, 1.95f).setCustomClientFactory(Cultist::new));
    public static final RegistryObject<EntityType<CursedNihilisticEvoker>> CURSED_NIHILISTIC_EVOKER = NoixmodAPIEntities.register("cursed_nihilistic_evoker", EntityType.Builder.<CursedNihilisticEvoker>of(CursedNihilisticEvoker::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(CursedNihilisticEvoker::new).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<DamageEntity>> DAMAGE_ENTITY = NoixmodAPIEntities.register("damage_entity", EntityType.Builder.of(DamageEntity::new, MobCategory.MISC).sized(0.7F, 0.2F).fireImmune().clientTrackingRange(8));
    public static final RegistryObject<EntityType<DanDa>> DAN_ZHEN = NoixmodAPIEntities.register("dan_zhen", EntityType.Builder.of(DanDa::new, MobCategory.MISC).sized(0.6F, 1.95f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<DeadIllagerSkull>> DEAD_ILLAGER_SKULL = NoixmodAPIEntities.register("dead_illager_skull", EntityType.Builder.of(DeadIllagerSkull::new, MobCategory.MONSTER).sized(0.6F, 0.6F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<DrownedServant>> DROWNED_SERVANT = NoixmodAPIEntities.register("drowned_servant", EntityType.Builder.of(DrownedServant::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<EnderManServant>> ENDER_MAN_SERVANT = NoixmodAPIEntities.register("enderman_servant", EntityType.Builder.of(EnderManServant::new, MobCategory.MISC).sized(0.6F, 2.9F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<EvilSummoner>> EVIL_SUMMONER = NoixmodAPIEntities.register("evil_summoner", EntityType.Builder.of(EvilSummoner::new, MobCategory.MONSTER).clientTrackingRange(10).fireImmune().sized(0.6f, 1.96f));
    public static final RegistryObject<EntityType<EvokerServant>> EVOKER_SERVANT = register("evoker_servant", EntityType.Builder.of(EvokerServant::new, MobCategory.MISC).sized(0.6f, 1.95f).setTrackingRange(8));
    public static final RegistryObject<EntityType<Exorcist>> EXORCIST = NoixmodAPIEntities.register("exorcist", EntityType.Builder.of(Exorcist::new, MobCategory.MISC).sized(0.6F, 1.96F).clientTrackingRange(8).fireImmune());
    public static final RegistryObject<EntityType<Fighter>> FIGHTER = NoixmodAPIEntities.register("fighter", EntityType.Builder.<Fighter>of(Fighter::new, MobCategory.MONSTER).setTrackingRange(64).sized(0.6f, 1.95f).setCustomClientFactory(Fighter::new).updateInterval(2));
    public static final RegistryObject<EntityType<Flagman>> FLAGMAN = NoixmodAPIEntities.register("flagman", EntityType.Builder.of(Flagman::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<GirlGhost>> GIRL_GHOST = NoixmodAPIEntities.register("girl_ghost", EntityType.Builder.of(GirlGhost::new, MobCategory.MONSTER).sized(0.6F, 1.9F).fireImmune().clientTrackingRange(8));
    public static final RegistryObject<EntityType<Golem>> GOLEM = register("golem", EntityType.Builder.of(Golem::new, MobCategory.MONSTER).sized(0.6f, 1.95f).fireImmune());
    public static final RegistryObject<EntityType<GraveGhost>> GRAVE_GHOST = NoixmodAPIEntities.register("grave_ghost", EntityType.Builder.of(GraveGhost::new, MobCategory.MONSTER).sized(0.6F, 1.96F));
    public static final RegistryObject<EntityType<GraveKeeper>> GRAVE_KEEPER = NoixmodAPIEntities.register("grave_keeper", EntityType.Builder.of(GraveKeeper::new, MobCategory.MONSTER).sized(0.6F, 1.97F));
    public static final RegistryObject<EntityType<GreenSinger>> GREEN_SINGER = NoixmodAPIEntities.register("green_singer", EntityType.Builder.of(GreenSinger::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<HeadHunterSword>> HHS = NoixmodAPIEntities.register("head_hunter_sword", EntityType.Builder.of(HeadHunterSword::new, MobCategory.MISC).sized(0.6f, 1.5f));
    public static final RegistryObject<EntityType<Healing>> HEALING = register("healling", EntityType.Builder.of(Healing::new, MobCategory.MISC).sized(0.35F, 0.6F).clientTrackingRange(8).updateInterval(2));
    public static final RegistryObject<EntityType<HorrorCamera>> HORROR_CAMERA = NoixmodAPIEntities.register("horror_camera", EntityType.Builder.of(HorrorCamera::new, MobCategory.MISC).fireImmune().clientTrackingRange(8).sized(0.5F, 0.5F));
    public static final RegistryObject<EntityType<HeadHunter>> OLD_HEAD_HUNTER = NoixmodAPIEntities.register("old_head_hunter", EntityType.Builder.of(HeadHunter::new, MobCategory.MONSTER).sized(0.8f, 3.95f).noSummon());
    public static final RegistryObject<EntityType<NewHeadHunter>> HEAD_HUNTER = register("headhunter", EntityType.Builder.of(NewHeadHunter::new, MobCategory.MONSTER).sized(0.6F, 2.1F));
    public static final RegistryObject<EntityType<HostileWindZombie>> H_WIND_ZOMBIE = register("hostile_wind_zombie", EntityType.Builder.of(HostileWindZombie::new, MobCategory.MONSTER).sized(0.6f, 1.95f).clientTrackingRange(9));
    public static final RegistryObject<EntityType<LittleFireball>> LITTLE_FIREBALL = NoixmodAPIEntities.register("little_fireball", EntityType.Builder.<LittleFireball>of(LittleFireball::new, MobCategory.MISC).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<MiniGhast>> MINI_GHAST = NoixmodAPIEntities.register("mini_ghast", EntityType.Builder.of(MiniGhast::new, MobCategory.MISC).sized(1.5f, 1.5f).setTrackingRange(64).updateInterval(2).fireImmune());
    public static final RegistryObject<EntityType<NetherSoul>> NETHER_SOUL = NoixmodAPIEntities.register("nether_soul", EntityType.Builder.of(NetherSoul::new, MobCategory.MONSTER).sized(0.6f, 1.95f).fireImmune().clientTrackingRange(8));
    public static final RegistryObject<EntityType<Mourner>> MOURNER = NoixmodAPIEntities.register("mourner",
            EntityType.Builder.of(Mourner::new, MobCategory.MONSTER).sized(0.6F, 1.95F).clientTrackingRange(8));public static final RegistryObject<EntityType<NihilisticArrow>> NIHILISTIC_ARROW = NoixmodAPIEntities.register("nihilistic_arrow", EntityType.Builder.<NihilisticArrow>of(NihilisticArrow::new, MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4));
    public static final RegistryObject<EntityType<NeoIllager>> NEO_ILLAGER = register("neo_illager", EntityType.Builder.of(NeoIllager::new, MobCategory.MISC)
            .sized(0.6F, 1.95F));
    public static final RegistryObject<EntityType<NihilisticArrowRain>> NIHILISTIC_ARROW_RAIN = NoixmodAPIEntities.register("nihilistic_arrow_rain", EntityType.Builder.of(NihilisticArrowRain::new, MobCategory.MISC).sized(4f, 0.3f));
    public static final RegistryObject<EntityType<NihilisticBlaze>> NIHILISTIC_BLAZE = NoixmodAPIEntities.register("nihilistic_blaze", EntityType.Builder.of(NihilisticBlaze::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<NihilisticGhast>> NIHILISTIC_GHAST = NoixmodAPIEntities.register("nihilistic_ghast", EntityType.Builder.of(NihilisticGhast::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).fireImmune().sized(2f, 2f));
    public static final RegistryObject<EntityType<NihilisticLord>> NIHILISTIC_LORD = NoixmodAPIEntities.register("nihilistic_lord", EntityType.Builder.of(NihilisticLord::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(1024).setUpdateInterval(3).fireImmune().sized(0.6f, 1.95f).noSummon());
    public static final RegistryObject<EntityType<NihilisticWither>> NIHILISTIC_WITHER = NoixmodAPIEntities.register("nihilistic_wither", EntityType.Builder.of(NihilisticWither::new, MobCategory.MONSTER).sized(0.9F, 3.5F).clientTrackingRange(10).fireImmune().immuneTo(Blocks.WITHER_ROSE));
    public static final RegistryObject<EntityType<NihilisticWitherBoss>> NIHILISTIC_WITHER_BOSS = register("nihilistic_wither_boss", EntityType.Builder.of(NihilisticWitherBoss::new, MobCategory.MONSTER).sized(0.9f, 3.5f).clientTrackingRange(10).fireImmune().immuneTo(Blocks.WITHER_ROSE));
    public static final RegistryObject<EntityType<NihilisticWitherSkull>> NIHILISTIC_WITHER_SKULL = NoixmodAPIEntities.register("nihilistic_wither_skull", EntityType.Builder.<NihilisticWitherSkull>of(NihilisticWitherSkull::new, MobCategory.MISC).sized(0.4f, 0.4f).clientTrackingRange(4).updateInterval(10));
    public static final RegistryObject<EntityType<NihilisticZombie>> NIHILISTIC_ZOMBIE = NoixmodAPIEntities.register("nihilistic_zombie", EntityType.Builder.of(NihilisticZombie::new, MobCategory.MONSTER).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<MoonKiller>> MOON_KILLER = register("moon_killer", EntityType.Builder.of(MoonKiller::new, MobCategory.MONSTER).sized(0.6F, 1.95F).noSummon());
    public static final RegistryObject<EntityType<PillagerServant>> PILLAGER_SERVANT = register("pillager_servant", EntityType.Builder.of(PillagerServant::new, MobCategory.MISC).sized(0.6f, 1.95f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<Priest>> PRIEST = register("priest", EntityType.Builder.of(Priest::new, MobCategory.MONSTER).sized(0.7f, 3.2F).fireImmune().clientTrackingRange(10));
    public static final RegistryObject<EntityType<Tracker>> TRACKER = register("tracker", EntityType.Builder.of(Tracker::new, MobCategory.MONSTER).sized(0.6F, 1.95F).fireImmune());
    public static final RegistryObject<EntityType<VillagerEvoker>> VILLAGER_EVOKER = NoixmodAPIEntities.register("villager_evoker", EntityType.Builder.of(VillagerEvoker::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<VillagerSpellcaster>> VILLAGER_SPELLCASTER = NoixmodAPIEntities.register("villager_spellcaster", EntityType.Builder.of(VillagerSpellcaster::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<WaterWarlock>> WATER_WARLOCK = NoixmodAPIEntities.register("water_warlock", EntityType.Builder.of(WaterWarlock::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<FreakyWorm>> FREAKY_WORM = NoixmodAPIEntities.register("freaky_worm", EntityType.Builder.<FreakyWorm>of(FreakyWorm::new, MobCategory.MONSTER).sized(1.6f, 1.2f));
    public static final RegistryObject<EntityType<FreakySkeleton>> FREAKY_SKELETON = NoixmodAPIEntities.register("freaky_skeleton", EntityType.Builder.<FreakySkeleton>of(FreakySkeleton::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<NihilisticFire>> NIHILISTIC_FIRE = NoixmodAPIEntities.register("nihilistic_fire", EntityType.Builder.<NihilisticFire>of(NihilisticFire::new, MobCategory.MISC).fireImmune().setTrackingRange(10).sized(1f, 1f));
    public static final RegistryObject<EntityType<NihilisticFireball>> NIHILISTIC_FIREBALL = NoixmodAPIEntities.register("nihilistic_fireball", EntityType.Builder.<NihilisticFireball>of(NihilisticFireball::new, MobCategory.MISC).setTrackingRange(10).sized(1f,1f).fireImmune());
    public static final RegistryObject<EntityType<Intruder>> INTRUDER = NoixmodAPIEntities.register("intruder", EntityType.Builder.of(Intruder::new, MobCategory.MONSTER).fireImmune().clientTrackingRange(10));
    public static final RegistryObject<EntityType<LavaZombieServant>> LAVA_ZOMBIE_SERVANT = NoixmodAPIEntities.register("lava_zombie_servant", EntityType.Builder.of(LavaZombieServant::new, MobCategory.MISC).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<Lurker>> LURKER = NoixmodAPIEntities.register("lurker", EntityType.Builder.<Lurker>of(Lurker::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).fireImmune().sized(1f, 1f));
    public static final RegistryObject<EntityType<VampireServant>> VAMPIRE_SERVANT = register("vampire_servant", EntityType.Builder.of(VampireServant::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<VexArcher>> VEX_ARCHER = NoixmodAPIEntities.register("vex_archer", EntityType.Builder.of(VexArcher::new, MobCategory.MISC).clientTrackingRange(8).fireImmune().sized(0.4F, 0.8F));
    public static final RegistryObject<EntityType<WardenServant>> WARDEN_SERVANT = register("warden_servant", EntityType.Builder.of(WardenServant::new, MobCategory.MISC).sized(0.9F, 2.9F).clientTrackingRange(16).fireImmune());
    public static final RegistryObject<EntityType<NihilisticEvoker>> NIHILISTIC_EVOKER = NoixmodAPIEntities.register("nihilistic_evoker", EntityType.Builder.<NihilisticEvoker>of(NihilisticEvoker::new, MobCategory.MONSTER).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<NihilisticServant>> NIHILISTIC_SERVANT = NoixmodAPIEntities.register("nihilistic_servant", EntityType.Builder.of(NihilisticServant::new, MobCategory.MISC).sized(0.6f, 1.95f).fireImmune());
    public static final RegistryObject<EntityType<LavaTrap>> LAVA_TRAP = NoixmodAPIEntities.register("lava_trap", EntityType.Builder.<LavaTrap>of(LavaTrap::new, MobCategory.MISC).sized(2F, 0.2F).fireImmune().clientTrackingRange(8));
    public static final RegistryObject<EntityType<StarGuardian>> STAR_GUARDIAN = NoixmodAPIEntities.register("star_guardian", EntityType.Builder.<StarGuardian>of(StarGuardian::new, MobCategory.MONSTER).sized(0.6F, 1.93F).setCustomClientFactory(StarGuardian::new).clientTrackingRange(20).fireImmune());
    public static final RegistryObject<EntityType<WaterTrap>> WATER_TRAP = NoixmodAPIEntities.register("water_trap", EntityType.Builder.<WaterTrap>of(WaterTrap::new, MobCategory.MISC).clientTrackingRange(6).updateInterval(2).sized(0.6f, 0.8f));
    public static final RegistryObject<EntityType<PlateauBeast>> PLATEAU_BEAST = NoixmodAPIEntities.register("plateau_beast", EntityType.Builder.<PlateauBeast>of(PlateauBeast::new, MobCategory.MONSTER).sized(1.25f, 1f));
    public static final RegistryObject<EntityType<NihilisticCrack>> NIHILISTIC_CRACK = register("nihilistic_crack", EntityType.Builder.of(NihilisticCrack::new, MobCategory.MISC).sized(0.5F, 0.5F));
    public static final RegistryObject<EntityType<NihilisticDeath>> NIHILISTIC_DEATH = NoixmodAPIEntities.register("nihilistic_death", EntityType.Builder.<NihilisticDeath>of(NihilisticDeath::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<RainbowphobiaPatients>> RAINBOWPHOBIA_PATIENTS = NoixmodAPIEntities.register("rainbowphobia_patients", EntityType.Builder.<RainbowphobiaPatients>of(RainbowphobiaPatients::new, MobCategory.MONSTER).clientTrackingRange(6).updateInterval(2).sized(0.6f, 1.95f).setCustomClientFactory(RainbowphobiaPatients::new));
    public static final RegistryObject<EntityType<EvokerIllager>> EVOKER_ILLAGER = NoixmodAPIEntities.register("evoker_illager", EntityType.Builder.<EvokerIllager>of(EvokerIllager::new, MobCategory.MONSTER).sized(0.6f, 1.95f).setCustomClientFactory(EvokerIllager::new).fireImmune());
    public static final RegistryObject<EntityType<VillagerMaster>> VILLAGER_MASTER = NoixmodAPIEntities.register("villager_master", EntityType.Builder.of(VillagerMaster::new, MobCategory.MISC).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<VillagerFangs>> VILLAGER_FANGS = NoixmodAPIEntities.register("villager_fangs",
            EntityType.Builder.of(VillagerFangs::new, MobCategory.MISC).sized(0.6F, 0.8F));
    public static final RegistryObject<EntityType<WitherSkeletonServant>> WITHER_SKELETON_SERVANT = NoixmodAPIEntities.register("wither_skeleton_servant", EntityType.Builder.of(WitherSkeletonServant::new, MobCategory.MISC).sized(0.6F, 2F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<PowerEntity>> POWER_ENTITY = NoixmodAPIEntities.register("power_entity", EntityType.Builder.<PowerEntity>of(PowerEntity::new, MobCategory.MISC).sized(0.7f, 0.7f));
    public static final RegistryObject<EntityType<VillagerGolem>> VILLAGER_GOLEM = NoixmodAPIEntities.register("villager_golem", EntityType.Builder.of(VillagerGolem::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).sized(1.4f, 2.7f).fireImmune());
    public static final RegistryObject<EntityType<NihilisticStatue>> NIHILISTIC_STATUE = NoixmodAPIEntities.register("nihilistic_statue", EntityType.Builder.<NihilisticStatue>of(NihilisticStatue::new, MobCategory.MISC).setCustomClientFactory(NihilisticStatue::new).setUpdateInterval(3).fireImmune().sized(0.5f, 3f));
    public static final RegistryObject<EntityType<MagicalClone>> MAGICAL_CLONE = NoixmodAPIEntities.register("magical_clone", EntityType.Builder.of(MagicalClone::new, MobCategory.MISC).sized(0.6f, 1.95f).updateInterval(2));
    public static final RegistryObject<EntityType<FreakySpider>> FREAKY_SPIDER = NoixmodAPIEntities.register("freaky_spider", EntityType.Builder.<FreakySpider>of(FreakySpider::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(10).setUpdateInterval(3).sized(1.4f, 0.9f).setCustomClientFactory(FreakySpider::new));
    public static final RegistryObject<EntityType<SmokeTrap>> SMOKE_TRAP = NoixmodAPIEntities.register("smoke_trap", EntityType.Builder.of(SmokeTrap::new, MobCategory.MISC).clientTrackingRange(6).updateInterval(2).sized(0.6f, 1f));
    public static final RegistryObject<EntityType<ThrownAxe>> THROWN_AXE = NoixmodAPIEntities.register("thrown_axe", EntityType.Builder.<ThrownAxe>of(ThrownAxe::new, MobCategory.MISC).sized(1F, 1F).clientTrackingRange(4).updateInterval(20));
    public static final RegistryObject<EntityType<SculkZombie>> SCULK_ZOMBIE = NoixmodAPIEntities.register("sculk_zombie", EntityType.Builder.of(SculkZombie::new, MobCategory.MISC).sized(0.6F, 1.95F).fireImmune());
    public static final RegistryObject<EntityType<ShadowWalker>> SHADOW_WALKER = register("shadow_walker", EntityType.Builder.of(ShadowWalker::new, MobCategory.MONSTER).sized(0.6f, 1.95f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<SilverfishServant>> SILVERFISH_SERVANT = register("silverfish_servant", EntityType.Builder.of(SilverfishServant::new, MobCategory.MISC).sized(0.4F, 0.3F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<SmallWorm>> SMALL_WORM = NoixmodAPIEntities.register("small_worm", EntityType.Builder.of(SmallWorm::new, MobCategory.MISC).sized(0.75f, 0.75f));
    public static final RegistryObject<EntityType<Superstitious>> SUPERSTITIOUS = NoixmodAPIEntities.register("superstitious", EntityType.Builder.of(Superstitious::new, MobCategory.MONSTER).sized(0.6F, 2F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<SuperstitiousClone>> SUPERSTITIOUS_CLONE = NoixmodAPIEntities.register("superstitious_clone", EntityType.Builder.of(SuperstitiousClone::new, MobCategory.MONSTER).sized(0.6F, 1.95F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<SwordCultist>> SWORD_CULTIST = NoixmodAPIEntities.register("sword_cultist", EntityType.Builder.of(SwordCultist::new, MobCategory.MONSTER).sized(0.6F, 2F).clientTrackingRange(8).fireImmune());
    public static final RegistryObject<EntityType<SuicideZombie>> SUICIDE_ZOMBIE = NoixmodAPIEntities.register("suicide_zombie", EntityType.Builder.<SuicideZombie>of(SuicideZombie::new, MobCategory.MISC).setCustomClientFactory(SuicideZombie::new).sized(0.6f, 1.95f).updateInterval(3).canSpawnFarFromPlayer());
    public static final RegistryObject<EntityType<SummonApostle>> SUMMON_APOSTLE = NoixmodAPIEntities.register("summon_apostle", EntityType.Builder.of(SummonApostle::new, MobCategory.MISC).sized(4f, 0.3f));
    public static final RegistryObject<EntityType<SummonEntity>> SUMMON_ENTITY = NoixmodAPIEntities.register("summon_entity", EntityType.Builder.of(SummonEntity::new, MobCategory.MISC).sized(1, 1));
    public static final RegistryObject<EntityType<SummonZhuan>> SUMMON_STAR_GUARDIAN = register("summon_star_guardian", EntityType.Builder.of(SummonZhuan::new, MobCategory.MISC).sized(4f, 0.3f));
    public static final RegistryObject<EntityType<VampireArrow>> VAMPIRE_ARROW = NoixmodAPIEntities.register("vampire_arrow", EntityType.Builder.<VampireArrow>of(VampireArrow::new, MobCategory.MISC).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<Vampire>> VAMPIRE = NoixmodAPIEntities.register("bloodsucker", EntityType.Builder.of(Vampire::new, MobCategory.MONSTER).sized(0.6f, 1.93f));
    public static final RegistryObject<EntityType<VexServant>> VEX_SERVANT = register("vex_servant", EntityType.Builder.of(VexServant::new, MobCategory.MISC).sized(0.4F, 0.8F).clientTrackingRange(8).fireImmune());
    public static final RegistryObject<EntityType<WindEntity>> WIND_ENTITY = register("wind_entity", EntityType.Builder.of(WindEntity::new, MobCategory.MISC).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<WindZombie>> WIND_ZOMBIE = register("wind_zombie", EntityType.Builder.of(WindZombie::new, MobCategory.MISC).sized(0.6f, 1.95f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<VindicatorServant>> VINDICATOR_SERVANT = register("vindicator_servant", EntityType.Builder.of(VindicatorServant::new, MobCategory.MISC).sized(0.6f, 1.96f).clientTrackingRange(8));
    public static final RegistryObject<EntityType<Worm>> WORM = NoixmodAPIEntities.register("worm", EntityType.Builder.<Worm>of(Worm::new, MobCategory.MISC).sized(1f, 1f));
    public static final RegistryObject<EntityType<WormMaster>> WORM_MASTER = register("worm_master", EntityType.Builder.of(WormMaster::new, MobCategory.MONSTER).sized(0.6f, 1.95f).clientTrackingRange(10));
    public static final RegistryObject<EntityType<WrongedSoul>> WRONGED_SOUL = NoixmodAPIEntities.register("wronged_soul", EntityType.Builder.of(WrongedSoul::new, MobCategory.MONSTER).fireImmune().sized(0.6f, 1.95f).setTrackingRange(12).canSpawnFarFromPlayer());
    public static final RegistryObject<EntityType<ZombieVindicator>> ZOMBIE_VINDICATOR = NoixmodAPIEntities.register("zombie_vindicator", EntityType.Builder.of(ZombieVindicator::new, MobCategory.MONSTER).sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<MushroomSpider>> MUSHROOM_SPIDER = NoixmodAPIEntities.register("mushroom_spider", EntityType.Builder.of(MushroomSpider::new, MobCategory.MISC).sized(1.4F, 0.9F));
    public static final RegistryObject<EntityType<Hunter>> HUNTER = NoixmodAPIEntities.register("hunter", EntityType.Builder.of(Hunter::new, MobCategory.MONSTER).sized(0.6F, 1.95F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<Drunkenness>> DRUNKENNESS = NoixmodAPIEntities.register("drunkenness", EntityType.Builder.of(Drunkenness::new, MobCategory.MONSTER).sized(0.6F, 1.95F).clientTrackingRange(8));
    public static final RegistryObject<EntityType<Detractor>> DETRACTOR = NoixmodAPIEntities.register("detractor", EntityType.Builder.of(Detractor::new, MobCategory.MONSTER).sized(0.6F, 2F).fireImmune().clientTrackingRange(12));

    private NoixmodAPIEntities(){}

    public static <T extends Entity> RegistryObject<EntityType<T>> register(String registryName, EntityType.Builder<T> entityTypeBuilder) {
        return REGISTRY.register(registryName, () -> entityTypeBuilder.build(registryName));
    }

    @SubscribeEvent
    public static void init(FMLCommonSetupEvent event) {
        event.enqueueWork(() -> {
            Armorer.init();
            Biologist.init();
            Bugler.init();
            Drunkenness.initialize();
            EvokerIllager.init();
            Flagman.initialize();
            GraveKeeper.initialize();
            Hunter.init();
            Mourner.init();
        });
    }

    @SubscribeEvent
    public static void registerAttributes(EntityAttributeCreationEvent event) {
        event.put(ABOMINATION.get(), Abomination.createAttributes().build());
        event.put(ABYSS.get(), Abyss.createAttributes());
        event.put(AMBUSHER.get(), NoixmodAPIAttributes.createAmbusherAttributes().build());
        event.put(APOSTLE.get(), Apostle.createAttributes().build());
        event.put(APOSTLE_SERVANT.get(), ApostleServant.createAttributes().build());
        event.put(APOSTLE_SHADOW.get(), ApostleShadow.createAttributes().build());
        event.put(AQUATIC_WORM.get(), AquaticWorm.createAttributes().build());
        event.put(ARCHER_SERVANT.get(), ArcherServant.createAttributes());
        event.put(ARMORER.get(), NoixmodAPIAttributes.createArmorerAttributes().build());
        event.put(BIOLOGIST.get(), Biologist.createAttributes().build());
        event.put(CREEPER_SERVANT.get(), CreeperServant.createAttributes().build());
        event.put(CULTIST.get(), Cultist.createAttributes().build());
        event.put(CURSED_NIHILISTIC_EVOKER.get(), CursedNihilisticEvoker.createAttributes().build());
        event.put(DAN_ZHEN.get(), DanDa.createAttributes().build());
        event.put(DEAD_ILLAGER_SKULL.get(), NoixmodAPIAttributes.createDIKAttributes().build());
        event.put(DETRACTOR.get(), NoixmodAPIAttributes.createDetractorAttributes().build());
        event.put(DROWNED_SERVANT.get(), NoixmodAPIAttributes.createDrownedAttributes().build());
        event.put(DRUNKENNESS.get(), NoixmodAPIAttributes.createDrunkennessAttributes().build());
        event.put(ENDER_MAN_SERVANT.get(), NoixmodAPIAttributes.createEnderManAttributes().build());
        event.put(EVIL_SUMMONER.get(), EvilSummoner.createAttributes().build());
        event.put(EVOKER_ILLAGER.get(), EvokerIllager.createAttributes().build());
        event.put(EVOKER_SERVANT.get(), EvokerServant.createAttributes().build());
        event.put(EXORCIST.get(), NoixmodAPIAttributes.createExorcistAttributes().build());
        event.put(FIGHTER.get(), Fighter.createAttributes().build());
        event.put(FLAGMAN.get(), Flagman.createAttributes().build());
        event.put(FREAKY_SPIDER.get(), FreakySpider.createAttributes().build());
        event.put(FREAKY_WORM.get(), FreakyWorm.createAttributes().build());
        event.put(FREAKY_SKELETON.get(), FreakySkeleton.createAttributes().build());
        event.put(GIRL_GHOST.get(), NoixmodAPIAttributes.createGirlGhostAttributes().build());
        event.put(GOLEM.get(), Golem.createAttributes().build());
        event.put(GRAVE_GHOST.get(), GraveGhost.createAttributes().build());
        event.put(GRAVE_KEEPER.get(), GraveKeeper.createAttributes().build());
        event.put(GREEN_SINGER.get(), GreenSinger.createAttributes().build());
        event.put(OLD_HEAD_HUNTER.get(), HeadHunter.createAttributes().build());
        event.put(HEALING.get(), Healing.createAttributes());
        event.put(H_WIND_ZOMBIE.get(), WindZombie.createAttributes().build());
        event.put(HUNTER.get(), NoixmodAPIAttributes.createHunterAttributes().build());
        event.put(INTRUDER.get(), NoixmodAPIAttributes.createIntruderAttributes().build());
        event.put(LAVA_ZOMBIE_SERVANT.get(), NoixmodAPIAttributes.createLavaAttributes().build());
        event.put(LURKER.get(), Lurker.createAttributes().build());
        event.put(MAGICAL_CLONE.get(), MagicalClone.createAttributes().build());
        event.put(MINI_GHAST.get(), MiniGhast.createAttributes().build());
        event.put(MOON_KILLER.get(), MoonKiller.createAttributes().build());
        event.put(MOURNER.get(), NoixmodAPIAttributes.createMournerAttributes().build());
        event.put(MUSHROOM_SPIDER.get(), NoixmodAPIAttributes.createMushroomSpiderAttributes().build());
        event.put(PRIEST.get(), Priest.createAttributes());
        event.put(RAINBOWPHOBIA_PATIENTS.get(), RainbowphobiaPatients.createAttributes().build());
        event.put(NEO_ILLAGER.get(), NeoIllager.createAttributes().build());
        event.put(NETHER_SOUL.get(), NetherSoul.createAttributes().build());
        event.put(HEAD_HUNTER.get(), HeadHunter.createAttributes().build());
        event.put(NIHILISTIC_LORD.get(), NihilisticLord.createAttributes().build());
        event.put(NIHILISTIC_ZOMBIE.get(), NihilisticZombie.createAttributes().build());
        event.put(NIHILISTIC_GHAST.get(), NihilisticGhast.createAttributes().build());
        event.put(NIHILISTIC_BLAZE.get(), NihilisticBlaze.createAttributes().build());
        event.put(NIHILISTIC_DEATH.get(), NihilisticDeath.createAttributes().build());
        event.put(NIHILISTIC_EVOKER.get(), NihilisticEvoker.createAttributes().build());
        event.put(NIHILISTIC_SERVANT.get(), NihilisticServant.createAttributes().build());
        event.put(NIHILISTIC_STATUE.get(), NihilisticStatue.createAttributes().build());
        event.put(NIHILISTIC_WITHER.get(), NihilisticWither.createAttributes().build());
        event.put(NIHILISTIC_WITHER_BOSS.get(), NihilisticWither.createAttributes().build());
        event.put(PILLAGER_SERVANT.get(), PillagerServant.createAttributes());
        event.put(PLATEAU_BEAST.get(), PlateauBeast.createAttributes().build());
        event.put(POWER_ENTITY.get(), PowerEntity.createAttributes().build());
        event.put(SCULK_ZOMBIE.get(), SculkZombie.createAttributes().build());
        event.put(SHADOW_WALKER.get(), ShadowWalker.createAttributes().build());
        event.put(SILVERFISH_SERVANT.get(), SilverfishServant.createAttributes());
        event.put(SMALL_WORM.get(), SmallWorm.createAttributes().build());
        event.put(STAR_GUARDIAN.get(), StarGuardian.createAttributes().build());
        event.put(SUICIDE_ZOMBIE.get(), SuicideZombie.createAttributes().build());
        event.put(SUPERSTITIOUS.get(), NoixmodAPIAttributes.createSuperstitiousAttributes().build());
        event.put(SUPERSTITIOUS_CLONE.get(), NoixmodAPIAttributes.createSuperstitiousCloneAttributes().build());
        event.put(SWORD_CULTIST.get(), NoixmodAPIAttributes.createSwordCultistAttributes().build());
        event.put(TRACKER.get(), Tracker.createAttributes());
        event.put(BUGLER.get(), Bugler.createAttributes().build());
        event.put(VAMPIRE.get(), NoixmodAPIAttributes.createVampireAttributes().build());
        event.put(VAMPIRE_SERVANT.get(), VampireServant.createAttributes().build());
        event.put(VEX_ARCHER.get(), VexArcher.createAttributes().build());
        event.put(VEX_SERVANT.get(), VexServant.createAttributes().build());
        event.put(VINDICATOR_SERVANT.get(), VindicatorServant.createAttributes().build());
        event.put(VILLAGER_EVOKER.get(), VillagerEvoker.createAttributes().build());
        event.put(VILLAGER_GOLEM.get(), VillagerGolem.createAttributes().build());
        event.put(VILLAGER_MASTER.get(), VillagerMaster.createAttributes().build());
        event.put(VILLAGER_SPELLCASTER.get(), VillagerSpellcaster.createAttributes().build());
        event.put(WARDEN_SERVANT.get(), WardenServant.createAttributes().build());
        event.put(WATER_WARLOCK.get(), WaterWarlock.createAttributes().build());
        event.put(WIND_ZOMBIE.get(), WindZombie.createAttributes().build());
        event.put(WITHER_SKELETON_SERVANT.get(), NoixmodAPIAttributes.createWitherSkeletonServantAttributes().build());
        event.put(WORM.get(), Worm.createAttributes().build());
        event.put(WORM_MASTER.get(), WormMaster.createAttributes().build());
        event.put(WRONGED_SOUL.get(), WrongedSoul.createAttributes().build());
        event.put(ZOMBIE_VINDICATOR.get(), ZombieVindicator.createAttributes().build());
    }
}
