@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bilibili.player_ix.noixmod_api.entities.boss.star_guardian;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;