modLoader="javafml"
loaderVersion="[47,)"
license="GPLv2"

[[mods]]
modId="noixmodapi"
version="${mod_version}"
displayName="No.IXAPI"
displayURL="https://github.com/noixmod"
logoFile="logo.png"
credits="Programmer : Player_IX.Some textures by Illager-Wither"
authors="Player_IX"
description="A fun mod!"

[[dependencies.noixmodapi]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.noixmodapi]]
modId = "ix_api"
mandatory = true
versionRange = "[1.,)"
ordering = "AFTER"
side = "BOTH"