modLoader="javafml"
loaderVersion="[47,)"
license="GPL"

[[mods]]
modId="noixmodapi"
version="1.3.902-pre1"
displayName="No.IXAPI"
displayURL="https://github.com/noixmod"
logoFile="logo.png"
credits="Programmer : Player_IX.Some textures by Illager-Wither"
authors="Player_IX"
description="A fun mod!"

[[dependencies.noixmodapi]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"