@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bilibili.player_ix.noixmod_api.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;