@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bilibili.player_ix.noixmod_api.entities.monster.abstract_monster;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;