@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bilibili.player_ix.noixmod_api.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;